---
hostname:
  description: "Hostname for the NetBox server"
  type: "string"
  required: true

api_token:
  description: "API Token to use against the API"
  type: "string"
  required: true
  secret: true

use_https:
  description: "Use HTTPS when contacting the API"
  type: "boolean"
  required: true

ssl_verify:
  description: "Verify ssl/tls protocol certs when contacting the API."
  type: "boolean"
  required: true

default_fail_non_2xx:
  description: "Default behavior for NetBox HTTP actions: when true, actions will fail on non-2xx NetBox responses unless the per-action fail_non_2xx parameter is explicitly set."
  type: "boolean"
  required: false
  default: false

sensor_address:
  description: "Host address to run the Webhook sensor on."
  type: "string"
  default: "0.0.0.0"

sensor_port:
  description: "Port to run the Webhook sensor on."
  type: "integer"
  default: 6000

sensor_secret:
  description: "When provided, will force request signature verification using the provided secret value."
  type: "string"
  default: ""
  secret: true
